chatting:
  description: >
    {young_writer} just reached out with a super important ask:\n
    {inquiry}\n\n
    {person} from {young_writer} is the one that reached out.
    Make sure to use everything you know
    to provide the best support possible.
    You must strive to provide a complete 
    and accurate response to the young_writer's inquiry.
  expected_output: >
    A detailed, informative response to the
    young_writer's inquiry that addresses 
    all aspects of their question.\n
    Ask questions to learn young_writer's persona, 
    including name, age, gender, school grade, characteristcs.
    Pass yount_writer's inquiry to planner.
    Gather information from planner
    The response should include references,
    to everything you used to find the answer,
    including external data or solutions.
    Ensure the answer is complete,
    leaving no questions unanswered, and maintain a helpful and friendly
    tone throughout.
  agent: support_representative

quality_assurance_review:
  description: >
    Review the response drafted by the Senior Support Representative for {customer}'s inquiry.
    {young_writer} just reached out with a super important ask:\n
    {inquiry}\n\n
    {person} from {young_writer} is the one that reached out.
    Make sure to use everything you know
    to provide the best support possible.
    You must strive to provide a complete 
    and accurate response to the young_writer's inquiry.
  expected_output: >
    A detailed, informative response to the
    young_writer's inquiry that addresses 
    all aspects of their question.\n
    Ask questions to learn young_writer's persona, 
    including name, age, gender, school grade, characteristcs.
    Pass yount_writer's inquiry to planner.
    Gather information from planner
    The response should include references,
    to everything you used to find the answer,
    including external data or solutions.
    Ensure the answer is complete,
    leaving no questions unanswered, and maintain a helpful and friendly
    tone throughout.
  agent: support_representative

research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
    Make sure content is proper for age group of {young_writer}

  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

guidline_task:
  description:>
    Based on the result from support_representative and research,
    write a write plan for {topic}
    Organize writing plan into an introduction, body paragraphs, and a conclusion,
    making each paragraph focuses on a specific point related to {topic}.
    Create a plan for each paragraph, including the topic sentence, supporting evidence, and analysis.
  expected_output: >
    A write plan about {topic} follow literal school essay best practice. 
  agent: organizer


reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
    You are mainly reviews the user’s paper, provides pros, cons, and how to improve. 
    There will be multi-iterative in this step.
  agent: reviewer
