fetch_profile:
  description: "Load the profile for user '{user_id}'."
  expected_output: "A JSON blob with user profile information."
  agent: profile_manager


collect_writing_ideas:
  description: |
    You are helping the student prepare an essay on "{topic}".
    Ask engaging questions to gather their ideas.
    Use the student's profile to guide your questions.
  expected_output: "A tidy bullet-list of writing ideas"
  agent: conversation_guide


draft_outline:
  description: |
    Using the ideas gathered and the student's profile, create a numbered outline.
    Give each paragraph a short hint line.
  expected_output: "An ordered outline and hints."
  agent: outline_planner

deliver_outline :
  description: |
    Present the ordered outline and hints to the student.
    Store the essay student submitted as "draft_essay".
  expected_output: "{draft_essay}"
  agent: conversation_guide


evaluate_draft:
  description: |
    The student has submitted a draft essay.
    Score it (0-100) for grammar, clarity, structure, and topic compliance.
    Return **only** a JSON like:
    {% raw %}
    {
      "score": 88,
      "passed": true,
      "issues": ["…", "…"]
    }
    {% endraw %}
    Pass if score >= 80.
  expected_output: "A JSON object exactly in the form above."
  agent: reviewer


coach_improvements:
  description: |
    The draft needs work. Below are the issues detected by the reviewer.
    Use them to give concrete advice and encourage the student to rewrite
    and resubmit.
  expected_output: "Targeted feedback and rewrite instructions."
  agent: improvement_coach
  context: [evaluate_draft]   
  human_input: true

appraise_progress:
  description: |
    Congratulate the learner on the accepted essay about "{topic}".
    Compare briefly with past work and highlight at least one improvement.
  expected_output: "A short progress report."
  agent: progress_analyst

